planning_plugins:
  - ompl_interface/OMPLPlanner
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath
cr20_group:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRT
    - PRM
    - EST
    - LBKPIECE
    - BiEST
    - ProjEST
    - RRTstar
RRTConnect:
  type: geometric::RRTConnect
  range: 0.0
RRT:
  type: geometric::RRT
  range: 0.0
  goal_bias: 0.05
PRM:
  type: geometric::PRM
  max_nearest_neighbors: 10
EST:
  type: geometric::EST
  range: 0.0
  goal_bias: 0.05
LBKPIECE:
  type: geometric::LBKPIECE
  range: 0.0
  border_fraction: 0.9
BiEST:
  type: geometric::BiEST
  range: 0.0
ProjEST:
  type: geometric::ProjEST
  range: 0.0
  goal_bias: 0.05
RRTstar:
  type: geometric::RRTstar
  range: 0.0
  goal_bias: 0.05
  delay_collision_checking: 1
